### ISSUE TITLE
Mejora el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-alejandrasotoa#1]
Buen trabajo @alejandrasotoa !

Algunas pistas para acabarlo:

- [x] Mueve el `ul` dentro del componente TypeList
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Organiza los estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html: lang ;)

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by alejandrasotoa** [comment]
Hola Carlos, he añadido las mejoras al ejercicio además de un evento. Le agregaré más cosillas, pero para efectos de la evaluación, ya estaría todo. Espero tus comentarios, ¡gracias!

**Comment by oneeyedman** [comment]
Excelente trabajo, @alejandrasotoa!! Bien hecho!
